[package]
name = "bevy_dog"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3"}
bytemuck = { version = "1.16", features = [ "derive" ] }
uuid = { version = "1.12.1", features = ["v4"] }

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

